forge 'forge.puppetlabs.com'

mod 'puppetlabs/git',         '0.1.0'
mod 'puppetlabs/ntp',         '3.1.1'
mod 'puppetlabs/apt',         '1.6.0'
mod 'puppetlabs/concat',      '1.1.0'
mod 'puppetlabs/firewall',    '1.1.2'
mod 'puppetlabs/stdlib',      '4.2.2'
mod 'puppetlabs/passenger',   '0.2.0'
mod 'puppetlabs/postgresql',  '3.3.3'
mod 'puppetlabs/ruby',        '0.3.0'
mod 'puppetlabs/inifile',     '1.1.0'
mod 'jfryman/nginx',          '0.0.9'
mod 'richardc/datacat',       '0.6.0'
mod 'stankevich/python',      '1.7.5'
mod 'puppetlabs/apache',      '1.1.1'
mod 'puppetlabs/mysql',       '2.3.1'
mod 'puppetdb',               :git => "https://github.com/puppetlabs/puppetlabs-puppetdb.git",              :ref => 'cbcf042f5418ae1d8943588034f372817b3955cf'
mod 'puppet',                 :git => "https://github.com/nicolasbrechet/puppet-puppet.git",                :ref => 'master'
mod 'sudo',                   :git => 'https://github.com/saz/puppet-sudo.git',                             :ref => 'v3.0.1'
mod 'vcsrepo',                :git => "https://github.com/puppetlabs/puppetlabs-vcsrepo.git",               :ref => 'master'
mod 'puppetlabs_apt',         :git => 'https://github.com/puppetlabs-operations/puppet-puppetlabs_apt.git', :ref => '0.0.3'
mod 'puppetboard',            :git => 'https://github.com/nibalizer/puppet-module-puppetboard.git',         :ref => '2.5.0'
mod 'php',                    :git => 'https://github.com/jippi/puppet-php',                                :ref => 'master'
mod 'ssh',                    :git => 'https://github.com/saz/puppet-ssh',                                  :ref => 'master'
mod 'icinga2',                :git => 'https://github.com/Icinga/puppet-icinga2',                           :ref => 'master'
mod 'gitlab',                 :git => 'https://github.com/spuder/puppet-gitlab',                            :ref => 'v2.3.4'
#mod 'dashing',        :git => 'https://github.com/nicolasbrechet/puppet-dashing',                           :ref => 'multiple_changes'
mod 'fail2ban',               :git => 'https://github.com/nicolasbrechet/puppet-fail2ban',                  :ref => '3.0.x'

